# Generated by Django 4.2.5 on 2023-09-18 16:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Sinopsis')),
                ('time', models.IntegerField(verbose_name='Duración')),
                ('genre', models.CharField(max_length=150, verbose_name='Género')),
                ('image', models.ImageField(default='nul', upload_to='media/Películas', verbose_name='Portada')),
                ('release_date', models.IntegerField(verbose_name='Año de estreno')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Sinopsis')),
                ('seasons', models.IntegerField(verbose_name='Temporadas')),
                ('episodes', models.IntegerField(verbose_name='Episodios')),
                ('time', models.IntegerField(verbose_name='Duración')),
                ('genre', models.CharField(max_length=150, verbose_name='Género')),
                ('image', models.ImageField(default='nul', upload_to='media/Series', verbose_name='Portada')),
                ('release_date', models.IntegerField(verbose_name='Año de estreno')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Customed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Sinopsis')),
                ('seasons', models.IntegerField(verbose_name='Temporadas')),
                ('episodes', models.IntegerField(verbose_name='Episodios')),
                ('time', models.IntegerField(verbose_name='Duración')),
                ('genre', models.CharField(max_length=150, verbose_name='Género')),
                ('image', models.ImageField(default='nul', upload_to='', verbose_name='Portada')),
                ('release_date', models.IntegerField(verbose_name='Año de estreno')),
                ('category', models.CharField(max_length=8, verbose_name='Categoría')),
                ('seen', models.BooleanField(default=False, verbose_name='¿Vista?')),
                ('favorite', models.BooleanField(default=False, verbose_name='¿Favorita?')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contenido de usuario',
                'verbose_name_plural': 'Contenido de usuarios',
            },
        ),
    ]
