# Generated by Django 4.2.5 on 2023-09-18 17:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customed',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=600, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='customed',
            name='episodes',
            field=models.IntegerField(blank=True, verbose_name='Episodios'),
        ),
        migrations.AlterField(
            model_name='customed',
            name='genre',
            field=models.CharField(max_length=15, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='customed',
            name='release_date',
            field=models.IntegerField(max_length=4, verbose_name='Año de estreno'),
        ),
        migrations.AlterField(
            model_name='customed',
            name='seasons',
            field=models.IntegerField(blank=True, verbose_name='Temporadas'),
        ),
        migrations.AlterField(
            model_name='customed',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=600, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Aventuras', 'Aventuras'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Fantasía', 'Fantasía'), ('Musical', 'Musical'), ('Suspense', 'Suspense'), ('Terror', 'Terror'), ('Bélica', 'Bélica'), ('Policíaca', 'Policíaca'), ('Histórica', 'Histórica'), ('Western', 'Western'), ('Deportiva', 'Deportiva'), ('Animado', 'Animado')], max_length=15, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=600, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Aventuras', 'Aventuras'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Fantasía', 'Fantasía'), ('Musical', 'Musical'), ('Suspense', 'Suspense'), ('Terror', 'Terror'), ('Bélica', 'Bélica'), ('Policíaca', 'Policíaca'), ('Histórica', 'Histórica'), ('Western', 'Western'), ('Deportiva', 'Deportiva'), ('Animado', 'Animado')], max_length=15, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
