# Generated by Django 4.2.5 on 2023-09-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_customed_description_alter_customed_episodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customed',
            name='episodes',
            field=models.IntegerField(default=0, verbose_name='Episodios'),
        ),
        migrations.AlterField(
            model_name='customed',
            name='seasons',
            field=models.IntegerField(default=0, verbose_name='Temporadas'),
        ),
    ]
