# Generated by Django 4.2.5 on 2023-09-22 03:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_customed_episodes_alter_customed_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customed',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Sinopsis'),
        ),
    ]
