# Generated by Django 4.2.5 on 2023-09-25 16:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_customed_description_alter_film_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customed',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=600, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='customed',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=600, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=600, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
