# Generated by Django 4.2.5 on 2023-09-25 17:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_customed_description_alter_customed_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customed',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=650, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='customed',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=650, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Aventuras', 'Aventuras'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Fantástico', 'Fantástico'), ('Musical', 'Musical'), ('Suspense', 'Suspense'), ('Thriller', 'Thriller'), ('Terror', 'Terror'), ('Bélico', 'Bélico'), ('Policíaco', 'Policíaco'), ('Histórico', 'Histórico'), ('Western', 'Western'), ('Deportivo', 'Deportivo'), ('Animación', 'Animación')], max_length=15, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=650, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Aventuras', 'Aventuras'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Fantástico', 'Fantástico'), ('Musical', 'Musical'), ('Suspense', 'Suspense'), ('Thriller', 'Thriller'), ('Terror', 'Terror'), ('Bélico', 'Bélico'), ('Policíaco', 'Policíaco'), ('Histórico', 'Histórico'), ('Western', 'Western'), ('Deportivo', 'Deportivo'), ('Animación', 'Animación')], max_length=15, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Título'),
        ),
    ]
